config/routes.rb
Rails.application.routes.draw do

  root 'conversations#index'
  resources 'conversations', only: [:index, :create, :show, :destroy]
  resources 'messages', only: [:update]

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
# == Schema Information
#
# Table name: conversations
#
#  id         :integer          not null, primary key
#  topic      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Conversation < ApplicationRecord
    has_many :user_conversations
    has_many :messages, dependent: :destroy
    has_many :users, through: :user_conversations, dependent: :destroy

    validates :topic, presence: true
    
    def includes_user?(user)
        users.where(id: user).exists?
    end
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id              :integer          not null, primary key
#  body            :text
#  user_id         :integer
#  conversation_id :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable

  has_many :user_conversations
  has_many :conversations, through: :user_conversations

  def has_joined?(conversation)
    conversations.where(id: conversation).exists?
  end
end

app/models/user_conversation.rb
# == Schema Information
#
# Table name: user_conversations
#
#  id              :integer          not null, primary key
#  user_id         :integer
#  conversation_id :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class UserConversation < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  validates_uniqueness_of :user_id, scope: :conversation_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  # Shows a list of Conversations
  def index
    @conversations = Conversation.all
  end

  # Creates a new Conversation or Joins an existing Conversation
  def create
    # Get the topic
    topic = params[:topic]

    # Search for the topic in Conversation table
    conversation = Conversation.where(topic: topic).first
    
    # If topic does not exists, create the topic
    if !conversation
      @conversation = Conversation.new(topic: topic)
      @conversation.save

    # If topic exists, join the conversation
    else
      @conversation = Conversation.find(conversation.id)

      # If user is not yet in conversation, add user to conversation
      unless current_user.has_joined?(conversation)
        @conversation.users << current_user
        @conversation.save
      end
      
    end

    # Redirect to conversation show page
    redirect_to conversation_path(@conversation)
  end

  # Shows the conversation and its messages
  def show
    @conversation = Conversation.find(params[:id])
  end

  # Deletes a conversation and its messages
  def destroy
    @conversation = Conversation.find(params[:id])
    @conversation.destroy

    # Redirect to index
    redirect_to conversations_path
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def update
    conversation = Conversation.find(params[:conversation_id])
    conversation.messages << Message.new(user_id: current_user.id, body: params[:body])
    conversation.save

    redirect_to conversation_path(conversation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/conversations/create.html.erb
<h1>Conversations#create</h1>
<p>Find me in app/views/conversations/create.html.erb</p>

<%= @output %>

app/views/conversations/index.html.erb
<h1>Simple Chat for Rails</h1>

<div>
    <%= link_to("Logout #{current_user.email}", destroy_user_session_path, method: :delete) if user_signed_in? %>   
    <br><br>
</div>

<hr>

<div>
    <h2>New Conversations</h2>
    <%= form_with(url: conversations_url, local:true) do |f| %>
        <div>
            <%= f.label :topic %>
            <%= f.text_field :topic %> <%= f.submit 'Create or Join Conversation' %>
        </div>
    <% end %>
</div>

<hr>

<h2>All Active Conversations</h2>
<ul>
<% @conversations.each do |conversation| %>
    <li><%= link_to conversation.topic, conversation_path(conversation) %> | <%= link_to 'Delete conversation', conversation_path(conversation), method: :delete, data: { confirm: "Are you sure?" } %></li>
<% end %>
</ul>

app/views/conversations/show.html.erb
<h1>Topic: <%= @conversation.topic %></h1>

<% unless @conversation.messages.empty? %>
    <uL>
    <% @conversation.messages.each do |m| %>
        <li>
            <strong><%= m.user.email %>:</strong>
            <p><%= simple_format(m.body) %></p>
        </li>
    <% end %>
    </uL>
<% end %>


<%= form_with(url: message_path, method: :patch, local: true) do |f| %>
    <%= f.hidden_field :conversation_id, value: @conversation.id %>
    <div>
        Message<br>
        <%= f.text_area :body %>
    </div>
    <%= f.submit 'Send' %>
<% end %>

<br>
<%= link_to 'Back', conversations_path %>

<!-- Reload page every 10 secs -->
<!-- <script language="javascript" type="text/javascript">setTimeout("location.reload();",10000);</script> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/update.html.erb
<h1>Messages#update</h1>
<p>Find me in app/views/messages/update.html.erb</p>